const express = require("express");
const router = express.Router();
const Servercontroller = require("../controllers/controller");
router.post("/registration", Servercontroller.registration.bind(Servercontroller));
router.post("/weathersession", Servercontroller.weathersession.bind(Servercontroller));
router.get("/accesstosession", Servercontroller.accesstosession.bind(Servercontroller));
router.post("/currencychoice", Servercontroller.currencychoice.bind(Servercontroller));
router.get("/currencysend", Servercontroller.currencysend.bind(Servercontroller));
router.post("/getrefreshtime", Servercontroller.getrefreshtime.bind(Servercontroller));
router.post("/removefavmovie", Servercontroller.removefavmovie.bind(Servercontroller));
router.get("/zerothevalues", Servercontroller.zerothevalues.bind(Servercontroller));
router.post("/addfavmovie", Servercontroller.addfavmovie.bind(Servercontroller));
router.get("/receivefavmovie", Servercontroller.receivefavmovie.bind(Servercontroller));
router.post("/savefromfrontend", Servercontroller.savefromfrontend.bind(Servercontroller));
router.get("/sendtofrontend", Servercontroller.sendtofrontend.bind(Servercontroller));
router.post("/sessioninterests", Servercontroller.sessioninterests.bind(Servercontroller));
router.get("/sendinterests", Servercontroller.sendinterests.bind(Servercontroller));
router.get("/verifyemail", Servercontroller.verifyemail.bind(Servercontroller));
router.post("/checkemail", Servercontroller.checkemail.bind(Servercontroller));
router.post("/login", Servercontroller.login.bind(Servercontroller));
router.get("/checksession", Servercontroller.checksession.bind(Servercontroller));
router.post("/forgotpassword", Servercontroller.forgotpassword.bind(Servercontroller));
router.get("/resetpassword", Servercontroller.forgotpasswordverify.bind(Servercontroller));
router.post("/changepassword", Servercontroller.changepassword.bind(Servercontroller));
router.post("/changeLinkStatus", Servercontroller.changeLinkStatus.bind(Servercontroller));
router.post("/fetchlinkstatus", Servercontroller.fetchlinkstatus.bind(Servercontroller));
module.exports = router;